### ISSUE TITLE
Call to undefined method Fontis_Blog_Helper_Data::addRequestTag()

### ISSUE THREAD

**Issue by horninc** [fontis/fontis_blog#4]
I get the following message on Blog page load.

Error message
E_ERROR: Call to undefined method Fontis_Blog_Helper_Data::addRequestTag()

Stack trace
…Layout called at /var/app/current/app/code/community/Fontis/Blog/Block/
Rss.php (28)
…reLayout called at /var/app/current/app/code/core/Mage/Core/Block/
Abstract.php (293)
…:setLayout called at /var/app/current/app/code/core/Mage/Core/Model/
Layout.php (456)
…reateBlock called at /var/app/current/app/code/core/Mage/Core/Model/
Layout.php (472)
…::addBlock called at /var/app/current/app/code/core/Mage/Core/Model/
Layout.php (239)
…erateBlock called at /var/app/current/app/code/core/Mage/Core/Model/
Layout.php (205)
…alled at /var/app/current/app/code/core/Mage/Core/Controller/Varien/
Action.php (344)
…alled at /var/app/current/app/code/core/Mage/Core/Controller/Varien/
Action.php (269)
… /var/app/current/app/code/community/Fontis/Blog/controllers/
RssController.php (28)
…alled at /var/app/current/app/code/core/Mage/Core/Controller/Varien/
Action.php (418)
…/var/app/current/app/code/core/Mage/Core/Controller/Varien/Router/
Standard.php (250)
…called at /var/app/current/app/code/core/Mage/Core/Controller/Varien/
Front.php (172)
…ont::dispatch called at /var/app/current/app/code/core/Mage/Core/Model/
App.php (354)
in Mage_Core_Model_App::run called at /var/app/current/app/Mage.php (684)
in Mage::run called at /var/app/current/index.php (87)

If I look for addRequestTag() in the code I see Rss.php which has 

protected function _prepareLayout()
    {
        Mage::helper("blog")->addRequestTag(array(self::CACHE_TAG, Fontis_Blog_Helper_Data::GLOBAL_CACHE_TAG));
        return parent::_prepareLayout();
    }

on lines 26-30, but I indeed cannot find the definision of the function addRequestTag() itself.

**Comment by mwgamble** [comment]
Sorry for taking so long to get back to you. We believe this issue was rectified with the Version 2 release of the extension: https://github.com/fontis/fontis_blog/releases/tag/v2.0.0
